spring.application.name=crm
db.url=jdbc:h2:mem:gymcrm;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
db.username=sa
db.password=
hibernate.dialect=org.hibernate.dialect.H2Dialect
hibernate.hbm2ddl.auto=create-drop
hibernate.show_sql=false
storage.init.trainees-file=classpath:trainees-data.txt
storage.init.trainers-file=classpath:trainers-data.txt
