db:
  url: jdbc:h2:file:./data/gymcrm-dev
  username: sa
  password: ""

hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  hbm2ddl:
    auto: update
  show_sql: true

storage:
  init:
    trainees-file: classpath:trainees-data.txt
    trainers-file: classpath:trainers-data.txt

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus